### ISSUE TITLE
Haven broken

### ISSUE THREAD

**Issue by uhu79** [DrOgres/twdu#14] opened 2023-12-02 19:37 UTC
my Haven 
[fvtt-Actor-the-brewery-hY4AOVfCez6vdfAq.json](https://github.com/DrOgres/twdu/files/13537207/fvtt-Actor-the-brewery-hY4AOVfCez6vdfAq.json)
does not open anymore

last thing I did was updating the stored items with newly created items (I have created items for all the NPC gear that was not an item yet)

I tried exporting and importing, I tried in browser mode and desktop mode

**Comment by DrOgres** [comment] 2023-12-09 16:04
Something in your list of survivors was broken.  I deleted them here:
[fvtt-Actor-the-brewery-hY4AOVfCez6vdfAq.json](https://github.com/DrOgres/twdu/files/13624822/fvtt-Actor-the-brewery-hY4AOVfCez6vdfAq.json)

and it imports and opens fine.  debugging shows an issue with a name somewhere.  

i'd suggest importing from this file, re-adding your survivors and seeing if it works, if not, import and add one at a time and  send the specific survivor that breaks it.  there might be a character issue or something else I can chase down.

**Comment by uhu79** [comment] 2023-12-11 11:47
thx - I did import it, added all the survivors again - still works

thing is: I did also previously (to continue my game) recreate the same Haven with the same template used (Factory) same list of survivors, same items and even projects and it has not shown any issues since

so cannot recreate this

**Comment by DrOgres** [comment] 2023-12-11 14:01
ok well ten I'm going to close this for now.  if it crops up again let me know and we can try to hunt down the cause

**Closed by DrOgres** 2023-12-11 14:01 UTC
